# Generated by Django 5.2.5 on 2025-08-28 10:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(help_text='Aircraft registration (e.g., F-GABC)', max_length=10, unique=True)),
                ('type', models.CharField(help_text='Aircraft type (e.g., Cessna 152)', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('year_manufactured', models.IntegerField(blank=True, null=True)),
                ('total_time', models.DecimalField(decimal_places=1, default=0, help_text='Total aircraft time in hours', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_aerodrome', models.CharField(max_length=100)),
                ('arrival_aerodrome', models.CharField(max_length=100)),
                ('pilot_role', models.CharField(choices=[('PIC', 'Pilot in Command'), ('SIC', 'Second in Command'), ('DUAL', 'Dual Instruction'), ('SOLO', 'Solo Flight')], default='PIC', max_length=4)),
                ('conditions', models.CharField(choices=[('VFR', 'Visual Flight Rules'), ('IFR', 'Instrument Flight Rules'), ('SVFR', 'Special VFR')], default='VFR', max_length=4)),
                ('flight_type', models.CharField(choices=[('LOCAL', 'Local Flight'), ('CROSS_COUNTRY', 'Cross Country'), ('NIGHT', 'Night Flight'), ('INSTRUMENT', 'Instrument Flight'), ('TOWER', 'Tower Controlled'), ('UNCONTROLLED', 'Uncontrolled Airspace')], default='LOCAL', max_length=15)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('total_time', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('night_time', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('instrument_time', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('cross_country_time', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('instructor_name', models.CharField(blank=True, max_length=100)),
                ('instructor_rating', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('landings_day', models.PositiveIntegerField(default=0)),
                ('landings_night', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.aircraft')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['-date', '-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_type', models.CharField(blank=True, help_text='e.g., PPL, CPL, ATPL', max_length=50)),
                ('medical_class', models.CharField(blank=True, help_text='e.g., Class 1, Class 2', max_length=10)),
                ('medical_expiry', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('flight_school', models.CharField(blank=True, max_length=100)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='pilot_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
