# Generated by Django 5.2.5 on 2025-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='pilot_role',
            field=models.CharField(choices=[('PIC', 'Pilot in Command'), ('SIC', 'Second in Command'), ('SOLO', 'Solo Flight'), ('DUAL', 'Dual Instruction Received'), ('INSTR', 'Flight Instruction Given'), ('SP', 'Safety Pilot'), ('SIM', 'Simulator')], default='PIC', max_length=5),
        ),
    ]
