# Generated by Django 5.2.5 on 2025-09-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_customuser_alter_aircraft_options_and_more'),
    ]

    operations = [
        # Note: We can't add constraints to the built-in User model from another app
        # The email uniqueness is enforced through form validation and signals
    ]
