# Generated by Django 5.2.5 on 2025-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_add_email_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='engine_type',
            field=models.CharField(choices=[('SINGLE', 'Single Engine'), ('MULTI', 'Multi Engine')], default='SINGLE', help_text='Number of engines', max_length=6),
        ),
    ]
