# Generated by Django 5.2.5 on 2025-09-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_aircraft_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_registration',
            field=models.CharField(blank=True, help_text='Aircraft registration (preserved when aircraft is deleted)', max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.aircraft'),
        ),
    ]
