# Generated by Django 5.2.5 on 2025-09-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_populate_aircraft_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_engine_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single Engine'), ('MULTI', 'Multi Engine')], help_text='Aircraft engine type (preserved when aircraft is deleted)', max_length=6),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_manufacturer',
            field=models.CharField(blank=True, help_text='Aircraft manufacturer (preserved when aircraft is deleted)', max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_type',
            field=models.CharField(blank=True, help_text='Aircraft type (preserved when aircraft is deleted)', max_length=50),
        ),
    ]
