# Generated by Django 5.2.5 on 2025-09-02 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_populate_aircraft_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cross_country_time',
            field=models.IntegerField(default=0, help_text='Cross country time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instrument_time',
            field=models.IntegerField(default=0, help_text='Instrument time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='night_time',
            field=models.IntegerField(default=0, help_text='Night time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
