# Generated by Django 5.2.5 on 2025-09-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_alter_flight_cross_country_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='total_time',
        ),
    ]
