# Generated by Django 5.2.5 on 2025-09-02 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_remove_aircraft_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_type',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='instructor_rating',
        ),
        migrations.AddField(
            model_name='flight',
            name='copilot_time',
            field=models.IntegerField(default=0, help_text='Co-pilot time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='day_landings',
            field=models.PositiveIntegerField(default=0, help_text='Number of day landings'),
        ),
        migrations.AddField(
            model_name='flight',
            name='double_command_time',
            field=models.IntegerField(default=0, help_text='Double command time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='ifr_approaches',
            field=models.PositiveIntegerField(default=0, help_text='Number of IFR approaches'),
        ),
        migrations.AddField(
            model_name='flight',
            name='ifr_time',
            field=models.IntegerField(default=0, help_text='IFR time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='instructor_time',
            field=models.IntegerField(default=0, help_text='Instructor time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='multi_engine_time',
            field=models.IntegerField(default=0, help_text='Multi engine time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='multi_pilot_time',
            field=models.IntegerField(default=0, help_text='Multi-pilot flight time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='night_landings',
            field=models.PositiveIntegerField(default=0, help_text='Number of night landings'),
        ),
        migrations.AddField(
            model_name='flight',
            name='pic_time',
            field=models.IntegerField(default=0, help_text='PIC time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='simulator_time',
            field=models.IntegerField(default=0, help_text='Simulator time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='simulator_type',
            field=models.CharField(blank=True, help_text='Type of simulator used', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='single_engine_time',
            field=models.IntegerField(default=0, help_text='Single engine time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cross_country_time',
            field=models.IntegerField(default=0, help_text='Cross country time in minutes (legacy)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instrument_time',
            field=models.IntegerField(default=0, help_text='Instrument time in minutes (legacy)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
