# Generated by Django 5.2.5 on 2025-09-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0012_remove_flight_conditions_remove_flight_flight_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='pilot_role',
        ),
    ]
