# Generated by Django 5.2.5 on 2025-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0013_remove_flight_pilot_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='ifr_approaches',
            field=models.PositiveIntegerField(default=0, help_text='Number of IFR approaches', verbose_name='IFR Approaches'),
        ),
    ]
