# Generated by Django 5.2.5 on 2025-09-02 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0014_alter_flight_ifr_approaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='ifr_time',
            field=models.IntegerField(default=0, help_text='IFR time in minutes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='IFR Time'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='pic_time',
            field=models.IntegerField(default=0, help_text='PIC time in minutes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='PIC Time'),
        ),
    ]
