# Generated by Django 5.2.5 on 2025-09-10 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0015_alter_flight_ifr_time_alter_flight_pic_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='total_time_minutes',
            field=models.IntegerField(default=0, help_text='Total flight time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
