# Generated by Django 5.2.5 on 2025-09-10 10:26

from django.db import migrations


def populate_total_time_minutes(apps, schema_editor):
    """Populate total_time_minutes field from existing total_time data"""
    Flight = apps.get_model('logbook', 'Flight')
    
    for flight in Flight.objects.all():
        if flight.total_time:
            # Convert decimal hours to minutes
            total_minutes = int(float(flight.total_time) * 60)
            flight.total_time_minutes = total_minutes
            flight.save(update_fields=['total_time_minutes'])


def reverse_populate_total_time_minutes(apps, schema_editor):
    """Reverse migration - set total_time_minutes to 0"""
    Flight = apps.get_model('logbook', 'Flight')
    
    for flight in Flight.objects.all():
        flight.total_time_minutes = 0
        flight.save(update_fields=['total_time_minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0016_add_total_time_minutes'),
    ]

    operations = [
        migrations.RunPython(
            populate_total_time_minutes,
            reverse_populate_total_time_minutes
        ),
    ]
